# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dang_nhap.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(675, 502)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.nen = QtWidgets.QWidget(self.centralwidget)
        self.nen.setGeometry(QtCore.QRect(-20, -20, 801, 571))
        self.nen.setAutoFillBackground(False)
        self.nen.setStyleSheet("background-color: #B6B6D5;")
        self.nen.setObjectName("nen")
        self.tieude1 = QtWidgets.QLabel(self.nen)
        self.tieude1.setGeometry(QtCore.QRect(80, 100, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.tieude1.setFont(font)
        self.tieude1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tieude1.setAutoFillBackground(False)
        self.tieude1.setStyleSheet("#tieude1 {\n"
"    color: rgb(21, 36, 108);\n"
"    font-size: 24px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.tieude1.setObjectName("tieude1")
        self.tieude2 = QtWidgets.QLabel(self.nen)
        self.tieude2.setGeometry(QtCore.QRect(40, 190, 341, 111))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.tieude2.setFont(font)
        self.tieude2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tieude2.setStyleSheet("#tieude2 {\n"
"    color: rgb(21, 36, 108);\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.tieude2.setScaledContents(False)
        self.tieude2.setWordWrap(False)
        self.tieude2.setObjectName("tieude2")
        self.khung = QtWidgets.QWidget(self.nen)
        self.khung.setGeometry(QtCore.QRect(360, 70, 301, 361))
        self.khung.setStyleSheet("background-color: rgba(215, 215, 235, 120);\n"
"border: 1px solid rgba(180, 180, 200, 150);  /* viền nhẹ */\n"
"border-radius: 20px;                         /* bo góc */")
        self.khung.setObjectName("khung")
        self.nutquenmk = QtWidgets.QPushButton(self.khung)
        self.nutquenmk.setGeometry(QtCore.QRect(10, 280, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.nutquenmk.setFont(font)
        self.nutquenmk.setStyleSheet("background-color: rgba(215, 215, 235, 0);        /* Nền trong suốt */\n"
"border: 1px solid rgba(180, 180, 200, 0);  /* viền nhẹ */\n"
"")
        self.nutquenmk.setObjectName("nutquenmk")
        self.pushButton_3 = QtWidgets.QPushButton(self.khung)
        self.pushButton_3.setGeometry(QtCore.QRect(160, 280, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: rgba(215, 215, 235, 0);        /* Nền trong suốt */\n"
"border: 1px solid rgba(180, 180, 200, 0);  /* viền nhẹ */\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.nutdangnhap = QtWidgets.QPushButton(self.khung)
        self.nutdangnhap.setGeometry(QtCore.QRect(20, 180, 261, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.nutdangnhap.setFont(font)
        self.nutdangnhap.setStyleSheet("background-color: #2E3A8D;   /* Màu nền */\n"
"border: 1px solid rgba(180, 180, 200, 150);  /* viền nhẹ */\n"
"border-radius: 12px;                         /* bo góc */\n"
"color: white; \n"
"")
        self.nutdangnhap.setObjectName("nutdangnhap")
        self.hienmk = QtWidgets.QCheckBox(self.khung)
        self.hienmk.setGeometry(QtCore.QRect(170, 240, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.hienmk.setFont(font)
        self.hienmk.setStyleSheet("background-color: rgba(215, 215, 235, 0);        /* Nền trong suốt */\n"
"border: 1px solid rgba(180, 180, 200, 0);  /* viền nhẹ */\n"
"")
        self.hienmk.setObjectName("hienmk")
        self.nhapuser = QtWidgets.QLineEdit(self.khung)
        self.nhapuser.setGeometry(QtCore.QRect(20, 30, 261, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.nhapuser.setFont(font)
        self.nhapuser.setStyleSheet("background-color: #EFF0F8;   /* Màu nền */\n"
"border: 1px solid rgba(180, 180, 200, 150);  /* viền nhẹ */\n"
"border-radius: 12px;                         /* bo góc */\n"
"\n"
"")
        self.nhapuser.setText("")
        self.nhapuser.setObjectName("nhapuser")
        self.nhapmk = QtWidgets.QLineEdit(self.khung)
        self.nhapmk.setGeometry(QtCore.QRect(20, 100, 261, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.nhapmk.setFont(font)
        self.nhapmk.setStyleSheet("background-color: #EFF0F8;   /* Màu nền */\n"
"border: 1px solid rgba(180, 180, 200, 150);  /* viền nhẹ */\n"
"border-radius: 12px;                         /* bo góc */\n"
"\n"
"")
        self.nhapmk.setText("")
        self.nhapmk.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.nhapmk.setObjectName("nhapmk")
        self.tieude1_2 = QtWidgets.QLabel(self.nen)
        self.tieude1_2.setGeometry(QtCore.QRect(20, 140, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.tieude1_2.setFont(font)
        self.tieude1_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tieude1_2.setAutoFillBackground(False)
        self.tieude1_2.setStyleSheet("#tieude1 {\n"
"    color: rgb(21, 36, 108);\n"
"    font-size: 24px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.tieude1_2.setObjectName("tieude1_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 675, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tieude1.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">PHẦN MỀM</span></p><p align=\"center\"><br/></p></body></html>"))
        self.tieude2.setText(_translate("MainWindow", "Chào mừng bạn đến với hệ thống quản lý\n"
"                học viên thông minh!\n"
"        Vui lòng đăng nhập để tiếp tục "))
        self.nutquenmk.setText(_translate("MainWindow", "Quên mật khẩu?"))
        self.pushButton_3.setText(_translate("MainWindow", "Tạo tài khoản mới"))
        self.nutdangnhap.setText(_translate("MainWindow", "Đăng nhập"))
        self.hienmk.setText(_translate("MainWindow", "Hiện mật khẩu"))
        self.nhapuser.setPlaceholderText(_translate("MainWindow", "  Nhập tên hoặc mã người dùng"))
        self.nhapmk.setPlaceholderText(_translate("MainWindow", "  Nhập mật khẩu"))
        self.tieude1_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#15246c;\">QUẢN LÝ HỌC VIÊN</span></p></body></html>"))