# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Quen_mk.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(482, 653)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.nen = QtWidgets.QWidget(self.centralwidget)
        self.nen.setGeometry(QtCore.QRect(0, 0, 621, 631))
        self.nen.setAutoFillBackground(False)
        self.nen.setStyleSheet("background-color: #B6B6D5;")
        self.nen.setObjectName("nen")
        self.khung = QtWidgets.QWidget(self.nen)
        self.khung.setGeometry(QtCore.QRect(90, 150, 301, 361))
        self.khung.setStyleSheet("background-color: rgba(215, 215, 235, 120);\n"
"border: 1px solid rgba(180, 180, 200, 150);  /* viền nhẹ */\n"
"border-radius: 20px;                         /* bo góc */")
        self.khung.setObjectName("khung")
        self.hienmk = QtWidgets.QCheckBox(self.khung)
        self.hienmk.setGeometry(QtCore.QRect(150, 300, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.hienmk.setFont(font)
        self.hienmk.setStyleSheet("background-color: rgba(215, 215, 235, 0);        /* Nền trong suốt */\n"
"border: 1px solid rgba(180, 180, 200, 0);  /* viền nhẹ */\n"
"")
        self.hienmk.setObjectName("hienmk")
        self.nhapemail = QtWidgets.QLineEdit(self.khung)
        self.nhapemail.setGeometry(QtCore.QRect(20, 30, 261, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.nhapemail.setFont(font)
        self.nhapemail.setStyleSheet("background-color: #EFF0F8;   /* Màu nền */\n"
"border: 1px solid rgba(180, 180, 200, 150);  /* viền nhẹ */\n"
"border-radius: 12px;                         /* bo góc */")
        self.nhapemail.setObjectName("nhapemail")
        self.maxacnhan = QtWidgets.QLineEdit(self.khung)
        self.maxacnhan.setGeometry(QtCore.QRect(20, 90, 261, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.maxacnhan.setFont(font)
        self.maxacnhan.setStyleSheet("background-color: #EFF0F8;   /* Màu nền */\n"
"border: 1px solid rgba(180, 180, 200, 150);  /* viền nhẹ */\n"
"border-radius: 12px;                         /* bo góc */")
        self.maxacnhan.setObjectName("maxacnhan")
        self.nhapmkmoi = QtWidgets.QLineEdit(self.khung)
        self.nhapmkmoi.setGeometry(QtCore.QRect(20, 180, 261, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.nhapmkmoi.setFont(font)
        self.nhapmkmoi.setStyleSheet("background-color: #EFF0F8;   /* Màu nền */\n"
"border: 1px solid rgba(180, 180, 200, 150);  /* viền nhẹ */\n"
"border-radius: 12px;                         /* bo góc */")
        self.nhapmkmoi.setObjectName("nhapmkmoi")
        self.xacnhanmkmoi = QtWidgets.QLineEdit(self.khung)
        self.xacnhanmkmoi.setGeometry(QtCore.QRect(20, 240, 261, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.xacnhanmkmoi.setFont(font)
        self.xacnhanmkmoi.setStyleSheet("background-color: #EFF0F8;   /* Màu nền */\n"
"border: 1px solid rgba(180, 180, 200, 150);  /* viền nhẹ */\n"
"border-radius: 12px;                         /* bo góc */")
        self.xacnhanmkmoi.setObjectName("xacnhanmkmoi")
        self.nutthoat = QtWidgets.QPushButton(self.nen)
        self.nutthoat.setGeometry(QtCore.QRect(370, 540, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.nutthoat.setFont(font)
        self.nutthoat.setStyleSheet("background-color: #545FAA;        /* nền trắng */\n"
"color: white;  \n"
"border-radius: 10px;            /* bo góc */\n"
"")
        self.nutthoat.setIconSize(QtCore.QSize(18, 18))
        self.nutthoat.setObjectName("nutthoat")
        self.nutxacnhan = QtWidgets.QPushButton(self.nen)
        self.nutxacnhan.setGeometry(QtCore.QRect(250, 540, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.nutxacnhan.setFont(font)
        self.nutxacnhan.setStyleSheet("background-color: #545FAA;        /* nền trắng */\n"
"color: white;  \n"
"border-radius: 10px;            /* bo góc */\n"
"")
        self.nutxacnhan.setIconSize(QtCore.QSize(18, 18))
        self.nutxacnhan.setObjectName("nutxacnhan")
        self.label = QtWidgets.QLabel(self.nen)
        self.label.setGeometry(QtCore.QRect(0, 0, 621, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: #2E3A8D;\n"
"color: #DADAF0;               \n"
"")
        self.label.setObjectName("label")
        self.tieude1 = QtWidgets.QLabel(self.nen)
        self.tieude1.setGeometry(QtCore.QRect(110, 100, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.tieude1.setFont(font)
        self.tieude1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tieude1.setAutoFillBackground(False)
        self.tieude1.setStyleSheet("#tieude1 {\n"
"    color: rgb(21, 36, 108);\n"
"    font-size: 24px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.tieude1.setObjectName("tieude1")
        self.label_2 = QtWidgets.QLabel(self.nen)
        self.label_2.setGeometry(QtCore.QRect(150, 60, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("#tieude1 {\n"
"    color: rgb(21, 36, 108);\n"
"    font-size: 24px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 482, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.hienmk.setText(_translate("MainWindow", "Hiện mật khẩu"))
        self.nhapemail.setPlaceholderText(_translate("MainWindow", "  Nhập email để lấy mã xác nhận"))
        self.maxacnhan.setPlaceholderText(_translate("MainWindow", "  Nhập mã xác nhận"))
        self.nhapmkmoi.setPlaceholderText(_translate("MainWindow", "   Nhập mật khẩu mới"))
        self.xacnhanmkmoi.setPlaceholderText(_translate("MainWindow", "   Xác nhận mật khẩu mới"))
        self.nutthoat.setText(_translate("MainWindow", "Thoát"))
        self.nutxacnhan.setText(_translate("MainWindow", "Xác nhận"))
        self.label.setText(_translate("MainWindow", "    Lấy lại mật khẩu"))
        self.tieude1.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">QUẢN LÝ HỌC VIÊN</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; color:#15246c;\">PHẦN MỀM </span></p></body></html>"))
